name: unit tests

on:
  push:
  pull_request:
    types: [opened]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: npm run unit
      run: |
        npm install
        npm run unit
